Added an ability to use null values for iaq in the sensors
PlaceOS/drivers pull request #269
Opened 2021-11-10 06:27 UTC by grkek

2021-11-10 13:34 UTC, caspiano requested changes

2021-11-10 13:34 UTC, caspiano commented on drivers/vergesense/location_service.cr
> +              iaq.nil? ? nil : iaq.not_nil!.value
```suggestion
              space.environment.try(&.iaq.try(&.value))
```

2021-11-10 13:34 UTC, caspiano commented on drivers/vergesense/room_sensor.cr
> +    iaq = floor_space.environment.try &.iaq
```suggestion
```

2021-11-10 13:34 UTC, caspiano commented on drivers/vergesense/room_sensor.cr
> +    self[:air_quality] = iaq.nil? ? nil : iaq.not_nil!.value
```suggestion
    self[:air_quality] = floor_space.environment.try(&.iaq.try(&.value))
```

Not ideal, but maybe it's worth allowing the other sensors to be nil, and creating a helper that can warn when an integration is not returning values. Suggestion below might be a bit overkill

```crystal
module Vergesense
  struct Environment
    {% begin %}
    {% for reading in [iaq, temperature, humidity] %}
      getter {{ reading }} : Sensor?
      
      def read_{{ reading }}
        if reading = {{ reading }}
          reading.value
        else
          Log.warn { "missing reading for {{ reading }}" }
          nil
        end
      end
    {% end %}
    {% end %}
  end
end
```

2021-11-10 13:34 UTC, caspiano commented on drivers/vergesense/room_sensor.cr
> +              iaq.nil? ? nil : iaq.not_nil!.value
Ditto suggestion as previous iag access.

2021-11-16 13:13 UTC, stakach commented on drivers/vergesense/room_sensor.cr
> +              iaq.nil? ? nil : iaq.not_nil!.value
```suggestion
              space.environment.try(&.iaq.try(&.value))
```

2021-11-16 13:19 UTC, merged