feat(placeos/mailers): ISE network creds in Event and Booking emails
PlaceOS/drivers pull request #405
Opened 2022-12-20 08:26 UTC by w-le

DRAFT
Not tested e2e yet.
Seeking review/advice.

1. New Event Mailer logic driver that **subscribes** to Bookings.bookings in given Zones, filters today's events and send the Host a welcome email with optional network creds.

2. Edit existing Booking Notifier logic driver so that network creds can optionally be generated and included in the Booking notification emails.

2022-12-20 10:07 UTC, grkek requested changes

2022-12-20 10:07 UTC, grkek commented on drivers/place/event_mailer.cr
> +    return {response["name"], response["password"]} unless response["error"]
You need to update the password for the returned user since the password is returned as ***** and not clear-text.

2022-12-20 11:20 UTC, grkek commented on drivers/place/event_mailer.cr
> +    return {response["name"], response["password"]} unless response["error"]
Use [this](https://github.com/PlaceOS/drivers/blob/master/drivers/cisco/ise/guests.cr#L188) or [this](https://github.com/PlaceOS/drivers/blob/master/drivers/cisco/ise/guests.cr#L202) to update the password of an already existing user.

2022-12-31 05:31 UTC, grkek requested changes
The code needs to be tested other than the issues I pointed out it LGTM

2022-12-31 05:31 UTC, grkek commented on drivers/cisco/ise/network_access.cr
> +    # Is there a one line way of doing this?
You can extend the `{name: name}` NamedTuple and provide the required JSON keys instead of assigning them one by one.

2022-12-31 05:31 UTC, grkek commented on drivers/cisco/ise/network_access.cr
> +  # Will be lowercase letters and numbers
This might be an issue since it needs one uppercase character and a symbol character to be present in the password

2022-12-31 05:31 UTC, grkek commented on drivers/place/booking_notifier.cr
> +  # It's a temporary password that changes each booking, so 6 chars (lowercase and numbers) is fine. We want it to be easy to briefly remember and type
Add an uppercase character and a symbol here as well

2023-01-09 07:59 UTC, w-le commented
hey @stakach are you free to review this on Tuesday Jan 10?

2023-01-18 12:23 UTC, merged