fix(PPT-1540): Update settings with proper names
PlaceOS/drivers pull request #521
Opened 2024-10-17 03:15 UTC by grkek

2024-10-17 03:19 UTC, stakach reviewed
this is a breaking change though... we'd need to investigate the impact on clients who have the old setting configured

2024-10-17 06:24 UTC, grkek commented
> this is a breaking change though... we'd need to investigate the impact on clients who have the old setting configured

I can put in a clause which will handle both of these

2024-10-17 21:04 UTC, stakach requested changes

2024-10-17 21:04 UTC, stakach commented on drivers/place/bookings.cr
>      hide_qr_code:               false,
We should remove the old setting from the defaults
Otherwise looks good

2024-10-27 21:05 UTC, stakach requested changes
needs to be backwards compatible and the settings can't clash

2024-10-27 21:05 UTC, stakach commented on drivers/place/bookings.cr
> +    self[:show_qr_code] = !hide_qr_code || show_qr_code
The settings both kind of clash
i.e. by default hide_qr_code == true, but if show_qr_code is set to false then the setting won't be applied.

```suggestion
    self[:show_qr_code] = show_qr_code.nil? ? !hide_qr_code : show_qr_code
```

2024-10-27 21:05 UTC, stakach commented on drivers/place/bookings.cr
> +    show_qr_code = setting?(Bool, :show_qr_code) || false
```suggestion
    show_qr_code = setting?(Bool, :show_qr_code)
```

2024-12-04 03:17 UTC, merged